[Korali] --------------------------------------------------------------------
[Korali] Current Generation: #1
terminate called after throwing an instance of 'pybind11::error_already_set'
  what():  UnboundLocalError: local variable 'spec_now' referenced before assignment

At:
  /home/ubuntu/korali/examples/reinforcement.learning/flowControl_turb/flowControl_turb_code/_model/turb.py(308): rewardk
  /home/ubuntu/korali/examples/reinforcement.learning/flowControl_turb/flowControl_turb_code/_model/turb.py(59): <lambda>
  /home/ubuntu/korali/examples/reinforcement.learning/flowControl_turb/flowControl_turb_code/_model/environment.py(62): environment
  /home/ubuntu/korali/examples/reinforcement.learning/flowControl_turb/flowControl_turb_code/run-vracer-turb.py(47): <lambda>
  /home/ubuntu/korali/examples/reinforcement.learning/flowControl_turb/flowControl_turb_code/run-vracer-turb.py(127): <module>

